export const FETCH_LAUNCH = "FETCH_LAUNCH";
export const FETCH_LAUNCH_START = "FETCH_LAUNCH_START";
export const FETCH_LAUNCH_SUCCESS = "FETCH_LAUNCH_SUCCESS";
export const FETCH_LAUNCH_FAILED = "FETCH_LAUNCH_FAILED";
export const APPLY_LAUNCH_FILTER = "APPLY_LAUNCH_FILTER";
